namespace TMS.Apps.Web.OutVidious.Common.ProvidersCore.Contracts;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public sealed record CaptionInfo
{
    /// <summary>
    /// Display label for the caption (e.g., "English", "Spanish (auto-generated)").
    /// </summary>
    public required string Label { get; init; }

    /// <summary>
    /// ISO language code (e.g., "en", "es").
    /// </summary>
    public required string LanguageCode { get; init; }

    /// <summary>
    /// URL to download the caption file.
    /// </summary>
    public required Uri Url { get; init; }

    /// <summary>
    /// Whether this caption track is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; init; }
}
