using TMS.Apps.FrontTube.Backend.Common.ProviderCore.Interfaces;

namespace TMS.Apps.FrontTube.Backend.Common.ProviderCore.Contracts;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public sealed record CaptionMetadataCommon : ICacheableCommon // TODO: Add Base Contract, with identity
{
    /// <summary>
    /// Display label for the caption (e.g., "English", "Spanish (auto-generated)").
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// ISO language code (e.g., "en", "es").
    /// </summary>
    public required string LanguageCode { get; init; }

    public required RemoteIdentityCommon RemoteIdentity { get; init; }

    /// <summary>
    /// Whether this caption track is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    public bool IsMetaData => true;
}
