using TMS.Apps.FrontTube.Backend.Common.ProviderCore.Cache;
using TMS.Apps.FrontTube.Backend.Common.ProviderCore.Interfaces;

namespace TMS.Apps.FrontTube.Backend.Common.ProviderCore.Contracts;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public sealed record CaptionMetadata : ICacheableCommon // TODO: Add Base Contract, with identity
{
    /// <summary>
    /// Display label for the caption (e.g., "English", "Spanish (auto-generated)").
    /// </summary>
    public required string Name { get; init; }

    /// <summary>
    /// ISO language code (e.g., "en", "es").
    /// </summary>
    public required string LanguageCode { get; init; }

    /// <summary>
    /// Absolute URL to download the caption file.
    /// </summary>
    public required Uri AbsoluteRemoteUrl { get; init; }

    /// <summary>
    /// Whether this caption track is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; init; }

    public bool IsMetaData => true;

        private long? _hash;
    public long Hash => _hash ??= HashHelper.ComputeHash(AbsoluteRemoteUrl.ToString());
    
}
