using TMS.Apps.FrontTube.Backend.Repository.DataBase.Interfaces;

namespace TMS.Apps.FrontTube.Backend.Repository.DataBase.Entities;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public class CaptionEntity : TrackableEntitiesBase , ICacheableEntity
{
    //public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastSyncedAt { get; set; }

    /// <summary>
    /// XxHash64 hash of the absolute remote URL for unique lookup.
    /// </summary>
    public long Hash { get; set; }

    public int VideoId { get; set; }

    /// <summary>
    /// Caption label (e.g., "English", "English (auto-generated)").
    /// </summary>
    public required string Label { get; set; }

    /// <summary>
    /// Language code (e.g., "en", "es", "fr").
    /// </summary>
    public required string LanguageCode { get; set; }

    /// <summary>
    /// Whether this caption is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Absolute URL to the caption file.
    /// </summary>
    public required string AbsoluteRemoteUrl { get; set; }

    /// <summary>
    /// Cached caption content (e.g., VTT format).
    /// </summary>
    public string? Text { get; set; }

    // Navigation property
    public VideoEntity Video { get; set; } = null!;
}
