namespace TMS.Apps.FTube.Backend.DataBase.Entities;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public class VideoCaptionEntity
{
    public int Id { get; set; }

    public int VideoId { get; set; }

    /// <summary>
    /// Caption label (e.g., "English", "English (auto-generated)").
    /// </summary>
    public required string Label { get; set; }

    /// <summary>
    /// Language code (e.g., "en", "es", "fr").
    /// </summary>
    public required string LanguageCode { get; set; }

    /// <summary>
    /// Whether this caption is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// URL to the caption file.
    /// </summary>
    public string? RemoteUrl { get; set; }

    /// <summary>
    /// Cached caption content (e.g., VTT format).
    /// </summary>
    public string? CachedContent { get; set; }

    // Navigation property
    public VideoEntity Video { get; set; } = null!;
}
