using TMS.Apps.FrontTube.Backend.Repository.DataBase.Entities;
using TMS.Apps.FrontTube.Backend.Common.ProviderCore.Contracts;

namespace TMS.Apps.FrontTube.Backend.Repository.Cache.Mappers;

/// <summary>
/// Maps between database entities and provider contracts for captions.
/// </summary>
public static class CaptionEntityMapper
{
    /// <summary>
    /// Converts a VideoCaptionEntity to a CaptionInfo contract.
    /// </summary>
    public static Caption ToContract(VideoCaptionEntity entity)
    {
        ArgumentNullException.ThrowIfNull(entity);

        return new Caption
        {
            Name = entity.Label,
            LanguageCode = entity.LanguageCode,
            RemoteUrl = new Uri(entity.RemoteUrl ?? "about:blank", UriKind.RelativeOrAbsolute),
            IsAutoGenerated = entity.IsAutoGenerated
        };
    }

    /// <summary>
    /// Converts a CaptionInfo contract to a VideoCaptionEntity for database storage.
    /// </summary>
    public static VideoCaptionEntity ToEntity(Caption contract, int videoId)
    {
        ArgumentNullException.ThrowIfNull(contract);

        return new VideoCaptionEntity
        {
            VideoId = videoId,
            Label = contract.Name,
            LanguageCode = contract.LanguageCode,
            RemoteUrl = contract.RemoteUrl.ToString(),
            IsAutoGenerated = contract.IsAutoGenerated
        };
    }

    /// <summary>
    /// Updates an existing entity with data from a contract.
    /// </summary>
    public static void UpdateEntity(VideoCaptionEntity entity, Caption contract)
    {
        ArgumentNullException.ThrowIfNull(entity);
        ArgumentNullException.ThrowIfNull(contract);

        entity.Label = contract.Name;
        entity.LanguageCode = contract.LanguageCode;
        entity.RemoteUrl = contract.RemoteUrl.ToString();
        entity.IsAutoGenerated = contract.IsAutoGenerated;
    }
}
