namespace TMS.Apps.FrontTube.Backend.Providers.Invidious.DTOs;

/// <summary>
/// Channel search result from the Invidious API.
/// </summary>
internal sealed record SearchChannel
{
    public string Type { get; init; } = "channel";

    public string Author { get; init; } = string.Empty;

    public string AuthorId { get; init; } = string.Empty;

    public string AuthorUrl { get; init; } = string.Empty;

    public bool AuthorVerified { get; init; }

    public IReadOnlyList<AuthorThumbnail> AuthorThumbnails { get; init; } = [];

    public bool AutoGenerated { get; init; }

    public long SubCount { get; init; }

    public int VideoCount { get; init; }

    public string Description { get; init; } = string.Empty;

    public string DescriptionHtml { get; init; } = string.Empty;
}
