namespace TMS.Apps.Web.OutVidious.Providers.Invidious.ApiModels;

/// <summary>
/// Raw channel details DTO from the Invidious API.
/// </summary>
public sealed record InvidiousChannelDto
{
    public string Author { get; init; } = string.Empty;

    public string AuthorId { get; init; } = string.Empty;

    public string AuthorUrl { get; init; } = string.Empty;

    public IReadOnlyList<InvidiousAuthorThumbnailDto> AuthorThumbnails { get; init; } = [];

    public IReadOnlyList<InvidiousChannelBannerDto> AuthorBanners { get; init; } = [];

    public string? Description { get; init; }

    public string? DescriptionHtml { get; init; }

    public long SubCount { get; init; }

    public long TotalViews { get; init; }

    public long Joined { get; init; }

    public bool AutoGenerated { get; init; }

    public bool IsFamilyFriendly { get; init; }

    public IReadOnlyList<string> AllowedRegions { get; init; } = [];

    public IReadOnlyList<string> Tabs { get; init; } = [];

    public IReadOnlyList<InvidiousChannelVideoDto> LatestVideos { get; init; } = [];

    public IReadOnlyList<InvidiousRelatedChannelDto> RelatedChannels { get; init; } = [];
}
