namespace TMS.Apps.FrontTube.Backend.Repository.Data.Contracts;

/// <summary>
/// Represents a video caption/subtitle track.
/// </summary>
public sealed class CaptionDomain
{
    public int Id { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? LastSyncedAt { get; set; }

    public required RemoteIdentityDomain RemoteIdentity { get; set; }

    public int VideoId { get; set; }

    /// <summary>
    /// Caption label (e.g., "English", "English (auto-generated)").
    /// </summary>
    public string Label { get; set; } = string.Empty;

    /// <summary>
    /// Language code (e.g., "en", "es", "fr").
    /// </summary>
    public string LanguageCode { get; set; } = string.Empty;

    /// <summary>
    /// Whether this caption is auto-generated.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    /// <summary>
    /// Cached caption content (e.g., VTT format).
    /// </summary>
    public string? Text { get; set; }

    // Navigation property
    public VideoDomain? Video { get; set; }

    public string? FetchingError { get; set; }
}
