--
-- PostgreSQL database dump
--

\restrict rV8zTc9lXWsm1Xmff6GTO6HCh42kFpyY7djzu2e30KT3T7Nqe57IDmn0HYElrEb

-- Dumped from database version 16.11 (Debian 16.11-1.pgdg13+1)
-- Dumped by pg_dump version 16.11

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: channel; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.channel (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_synced_at timestamp with time zone NOT NULL,
    remote_id character varying(24) NOT NULL,
    title character varying(255) NOT NULL,
    alias character varying(255),
    description character varying(5000),
    description_html text,
    handle character varying(50),
    subscriber_count bigint,
    video_count integer,
    total_view_count bigint,
    joined_at timestamp with time zone,
    is_verified boolean NOT NULL,
    keywords character varying(1000)
);


ALTER TABLE public.channel OWNER TO root;

--
-- Name: channel_avatar_map; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.channel_avatar_map (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    image_id integer NOT NULL
);


ALTER TABLE public.channel_avatar_map OWNER TO root;

--
-- Name: channel_avatar_map_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.channel_avatar_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_avatar_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channel_banner_map; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.channel_banner_map (
    id integer NOT NULL,
    channel_id integer NOT NULL,
    image_id integer NOT NULL
);


ALTER TABLE public.channel_banner_map OWNER TO root;

--
-- Name: channel_banner_map_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.channel_banner_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_banner_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channel_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: enum_audio_codec; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_audio_codec (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_audio_codec OWNER TO root;

--
-- Name: enum_audio_quality; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_audio_quality (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_audio_quality OWNER TO root;

--
-- Name: enum_projection_type; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_projection_type (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_projection_type OWNER TO root;

--
-- Name: enum_stream_type; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_stream_type (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_stream_type OWNER TO root;

--
-- Name: enum_video_codec; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_video_codec (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_video_codec OWNER TO root;

--
-- Name: enum_video_container; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.enum_video_container (
    id integer NOT NULL,
    name character varying(50) NOT NULL
);


ALTER TABLE public.enum_video_container OWNER TO root;

--
-- Name: image; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.image (
    id integer NOT NULL,
    created_at timestamp with time zone,
    last_synced_at timestamp with time zone,
    remote_url character varying(2000) NOT NULL,
    data bytea,
    width integer,
    height integer,
    mime_type character varying(50)
);


ALTER TABLE public.image OWNER TO root;

--
-- Name: image_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_group; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_group (
    id integer NOT NULL,
    alias character varying(255) NOT NULL,
    parent_group_id integer,
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    modified_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.scoped_group OWNER TO root;

--
-- Name: scoped_group_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_local_playlist; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_local_playlist (
    id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    alias character varying(255) NOT NULL,
    description character varying(1000),
    is_built_in boolean NOT NULL,
    sort_order integer NOT NULL
);


ALTER TABLE public.scoped_local_playlist OWNER TO root;

--
-- Name: scoped_local_playlist_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_local_playlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_local_playlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_local_playlist_video_map; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_local_playlist_video_map (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    local_playlist_id integer NOT NULL,
    video_id integer NOT NULL,
    "position" integer NOT NULL
);


ALTER TABLE public.scoped_local_playlist_video_map OWNER TO root;

--
-- Name: scoped_local_playlist_video_map_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_local_playlist_video_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_local_playlist_video_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_subscription; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_subscription (
    id integer NOT NULL,
    user_id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    modified_at timestamp with time zone DEFAULT now() NOT NULL,
    channel_id integer NOT NULL,
    alias character varying(255),
    notifications_enabled boolean NOT NULL,
    notification_settings text,
    default_playback_speed real,
    default_sync_interval integer
);


ALTER TABLE public.scoped_subscription OWNER TO root;

--
-- Name: scoped_subscription_group_map; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_subscription_group_map (
    id integer NOT NULL,
    group_id integer NOT NULL,
    subscription_id integer NOT NULL
);


ALTER TABLE public.scoped_subscription_group_map OWNER TO root;

--
-- Name: scoped_subscription_group_map_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_subscription_group_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_subscription_group_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_subscription_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_subscription ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_subscription_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: scoped_watching_history; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.scoped_watching_history (
    id integer NOT NULL,
    user_id integer NOT NULL,
    started_at timestamp with time zone DEFAULT now() NOT NULL,
    last_watched_at timestamp with time zone,
    video_id integer NOT NULL,
    last_position integer NOT NULL,
    video_duration integer,
    marked_as_watched boolean NOT NULL,
    playback_speed real,
    video_quality_label character varying(20)
);


ALTER TABLE public.scoped_watching_history OWNER TO root;

--
-- Name: scoped_watching_history_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.scoped_watching_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.scoped_watching_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stream; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.stream (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_synced_at timestamp with time zone NOT NULL,
    video_id integer NOT NULL,
    url character varying(2000) NOT NULL,
    stream_type_id integer NOT NULL,
    container_id integer NOT NULL,
    video_codec_id integer,
    audio_codec_id integer,
    audio_quality_id integer,
    projection_type_id integer NOT NULL,
    quality_label character varying(20),
    width integer,
    height integer,
    frame_rate integer,
    bitrate bigint,
    content_length bigint,
    audio_sample_rate integer,
    audio_channels integer,
    mime_type character varying(100),
    itag integer
);


ALTER TABLE public.stream OWNER TO root;

--
-- Name: stream_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.stream ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stream_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public."user" (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."user" OWNER TO root;

--
-- Name: user_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public."user" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.video (
    id integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    last_synced_at timestamp with time zone NOT NULL,
    remote_id character varying(20) NOT NULL,
    title character varying(255) NOT NULL,
    description character varying(5000),
    description_html text,
    duration_seconds bigint NOT NULL,
    view_count bigint NOT NULL,
    likes_count bigint,
    dislikes_count bigint,
    published_at timestamp with time zone,
    genre character varying(100),
    keywords character varying(1000),
    is_live boolean NOT NULL,
    is_upcoming boolean NOT NULL,
    is_short boolean NOT NULL,
    is_watched boolean NOT NULL,
    channel_id integer
);


ALTER TABLE public.video OWNER TO root;

--
-- Name: video_caption; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.video_caption (
    id integer NOT NULL,
    video_id integer NOT NULL,
    label character varying(100) NOT NULL,
    language_code character varying(10) NOT NULL,
    is_auto_generated boolean NOT NULL,
    remote_url character varying(2000),
    cached_content text
);


ALTER TABLE public.video_caption OWNER TO root;

--
-- Name: video_caption_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.video_caption ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.video_caption_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.video ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.video_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: video_thumbnail_map; Type: TABLE; Schema: public; Owner: root
--

CREATE TABLE public.video_thumbnail_map (
    id integer NOT NULL,
    video_id integer NOT NULL,
    image_id integer NOT NULL
);


ALTER TABLE public.video_thumbnail_map OWNER TO root;

--
-- Name: video_thumbnail_map_id_seq; Type: SEQUENCE; Schema: public; Owner: root
--

ALTER TABLE public.video_thumbnail_map ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.video_thumbnail_map_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: channel PK_channel; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel
    ADD CONSTRAINT "PK_channel" PRIMARY KEY (id);


--
-- Name: channel_avatar_map PK_channel_avatar_map; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_avatar_map
    ADD CONSTRAINT "PK_channel_avatar_map" PRIMARY KEY (id);


--
-- Name: channel_banner_map PK_channel_banner_map; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_banner_map
    ADD CONSTRAINT "PK_channel_banner_map" PRIMARY KEY (id);


--
-- Name: enum_audio_codec PK_enum_audio_codec; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_audio_codec
    ADD CONSTRAINT "PK_enum_audio_codec" PRIMARY KEY (id);


--
-- Name: enum_audio_quality PK_enum_audio_quality; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_audio_quality
    ADD CONSTRAINT "PK_enum_audio_quality" PRIMARY KEY (id);


--
-- Name: enum_projection_type PK_enum_projection_type; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_projection_type
    ADD CONSTRAINT "PK_enum_projection_type" PRIMARY KEY (id);


--
-- Name: enum_stream_type PK_enum_stream_type; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_stream_type
    ADD CONSTRAINT "PK_enum_stream_type" PRIMARY KEY (id);


--
-- Name: enum_video_codec PK_enum_video_codec; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_video_codec
    ADD CONSTRAINT "PK_enum_video_codec" PRIMARY KEY (id);


--
-- Name: enum_video_container PK_enum_video_container; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.enum_video_container
    ADD CONSTRAINT "PK_enum_video_container" PRIMARY KEY (id);


--
-- Name: image PK_image; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.image
    ADD CONSTRAINT "PK_image" PRIMARY KEY (id);


--
-- Name: scoped_group PK_scoped_group; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_group
    ADD CONSTRAINT "PK_scoped_group" PRIMARY KEY (id);


--
-- Name: scoped_local_playlist PK_scoped_local_playlist; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_local_playlist
    ADD CONSTRAINT "PK_scoped_local_playlist" PRIMARY KEY (id);


--
-- Name: scoped_local_playlist_video_map PK_scoped_local_playlist_video_map; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_local_playlist_video_map
    ADD CONSTRAINT "PK_scoped_local_playlist_video_map" PRIMARY KEY (id);


--
-- Name: scoped_subscription PK_scoped_subscription; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription
    ADD CONSTRAINT "PK_scoped_subscription" PRIMARY KEY (id);


--
-- Name: scoped_subscription_group_map PK_scoped_subscription_group_map; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription_group_map
    ADD CONSTRAINT "PK_scoped_subscription_group_map" PRIMARY KEY (id);


--
-- Name: scoped_watching_history PK_scoped_watching_history; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_watching_history
    ADD CONSTRAINT "PK_scoped_watching_history" PRIMARY KEY (id);


--
-- Name: stream PK_stream; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "PK_stream" PRIMARY KEY (id);


--
-- Name: user PK_user; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT "PK_user" PRIMARY KEY (id);


--
-- Name: video PK_video; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video
    ADD CONSTRAINT "PK_video" PRIMARY KEY (id);


--
-- Name: video_caption PK_video_caption; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video_caption
    ADD CONSTRAINT "PK_video_caption" PRIMARY KEY (id);


--
-- Name: video_thumbnail_map PK_video_thumbnail_map; Type: CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video_thumbnail_map
    ADD CONSTRAINT "PK_video_thumbnail_map" PRIMARY KEY (id);


--
-- Name: IX_channel_avatar_map_channel_id_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_channel_avatar_map_channel_id_image_id" ON public.channel_avatar_map USING btree (channel_id, image_id);


--
-- Name: IX_channel_avatar_map_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_channel_avatar_map_image_id" ON public.channel_avatar_map USING btree (image_id);


--
-- Name: IX_channel_banner_map_channel_id_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_channel_banner_map_channel_id_image_id" ON public.channel_banner_map USING btree (channel_id, image_id);


--
-- Name: IX_channel_banner_map_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_channel_banner_map_image_id" ON public.channel_banner_map USING btree (image_id);


--
-- Name: IX_channel_handle; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_channel_handle" ON public.channel USING btree (handle);


--
-- Name: IX_channel_remote_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_channel_remote_id" ON public.channel USING btree (remote_id);


--
-- Name: IX_enum_audio_codec_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_audio_codec_name" ON public.enum_audio_codec USING btree (name);


--
-- Name: IX_enum_audio_quality_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_audio_quality_name" ON public.enum_audio_quality USING btree (name);


--
-- Name: IX_enum_projection_type_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_projection_type_name" ON public.enum_projection_type USING btree (name);


--
-- Name: IX_enum_stream_type_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_stream_type_name" ON public.enum_stream_type USING btree (name);


--
-- Name: IX_enum_video_codec_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_video_codec_name" ON public.enum_video_codec USING btree (name);


--
-- Name: IX_enum_video_container_name; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_enum_video_container_name" ON public.enum_video_container USING btree (name);


--
-- Name: IX_image_remote_url; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_image_remote_url" ON public.image USING btree (remote_url);


--
-- Name: IX_scoped_group_parent_group_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_group_parent_group_id" ON public.scoped_group USING btree (parent_group_id);


--
-- Name: IX_scoped_group_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_group_user_id" ON public.scoped_group USING btree (user_id);


--
-- Name: IX_scoped_group_user_id_alias; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_group_user_id_alias" ON public.scoped_group USING btree (user_id, alias);


--
-- Name: IX_scoped_local_playlist_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_local_playlist_user_id" ON public.scoped_local_playlist USING btree (user_id);


--
-- Name: IX_scoped_local_playlist_user_id_alias; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_local_playlist_user_id_alias" ON public.scoped_local_playlist USING btree (user_id, alias);


--
-- Name: IX_scoped_local_playlist_video_map_local_playlist_id_position; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_local_playlist_video_map_local_playlist_id_position" ON public.scoped_local_playlist_video_map USING btree (local_playlist_id, "position");


--
-- Name: IX_scoped_local_playlist_video_map_local_playlist_id_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_scoped_local_playlist_video_map_local_playlist_id_video_id" ON public.scoped_local_playlist_video_map USING btree (local_playlist_id, video_id);


--
-- Name: IX_scoped_local_playlist_video_map_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_local_playlist_video_map_video_id" ON public.scoped_local_playlist_video_map USING btree (video_id);


--
-- Name: IX_scoped_subscription_channel_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_subscription_channel_id" ON public.scoped_subscription USING btree (channel_id);


--
-- Name: IX_scoped_subscription_group_map_group_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_subscription_group_map_group_id" ON public.scoped_subscription_group_map USING btree (group_id);


--
-- Name: IX_scoped_subscription_group_map_group_id_subscription_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_scoped_subscription_group_map_group_id_subscription_id" ON public.scoped_subscription_group_map USING btree (group_id, subscription_id);


--
-- Name: IX_scoped_subscription_group_map_subscription_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_subscription_group_map_subscription_id" ON public.scoped_subscription_group_map USING btree (subscription_id);


--
-- Name: IX_scoped_subscription_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_subscription_user_id" ON public.scoped_subscription USING btree (user_id);


--
-- Name: IX_scoped_subscription_user_id_channel_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_scoped_subscription_user_id_channel_id" ON public.scoped_subscription USING btree (user_id, channel_id);


--
-- Name: IX_scoped_watching_history_started_at; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_watching_history_started_at" ON public.scoped_watching_history USING btree (started_at);


--
-- Name: IX_scoped_watching_history_user_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_watching_history_user_id" ON public.scoped_watching_history USING btree (user_id);


--
-- Name: IX_scoped_watching_history_user_id_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_watching_history_user_id_video_id" ON public.scoped_watching_history USING btree (user_id, video_id);


--
-- Name: IX_scoped_watching_history_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_scoped_watching_history_video_id" ON public.scoped_watching_history USING btree (video_id);


--
-- Name: IX_stream_audio_codec_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_audio_codec_id" ON public.stream USING btree (audio_codec_id);


--
-- Name: IX_stream_audio_quality_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_audio_quality_id" ON public.stream USING btree (audio_quality_id);


--
-- Name: IX_stream_container_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_container_id" ON public.stream USING btree (container_id);


--
-- Name: IX_stream_projection_type_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_projection_type_id" ON public.stream USING btree (projection_type_id);


--
-- Name: IX_stream_stream_type_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_stream_type_id" ON public.stream USING btree (stream_type_id);


--
-- Name: IX_stream_video_codec_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_video_codec_id" ON public.stream USING btree (video_codec_id);


--
-- Name: IX_stream_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_stream_video_id" ON public.stream USING btree (video_id);


--
-- Name: IX_stream_video_id_itag; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_stream_video_id_itag" ON public.stream USING btree (video_id, itag);


--
-- Name: IX_user_name; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_user_name" ON public."user" USING btree (name);


--
-- Name: IX_video_caption_video_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_video_caption_video_id" ON public.video_caption USING btree (video_id);


--
-- Name: IX_video_caption_video_id_language_code; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_video_caption_video_id_language_code" ON public.video_caption USING btree (video_id, language_code);


--
-- Name: IX_video_channel_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_video_channel_id" ON public.video USING btree (channel_id);


--
-- Name: IX_video_published_at; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_video_published_at" ON public.video USING btree (published_at);


--
-- Name: IX_video_remote_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_video_remote_id" ON public.video USING btree (remote_id);


--
-- Name: IX_video_thumbnail_map_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE INDEX "IX_video_thumbnail_map_image_id" ON public.video_thumbnail_map USING btree (image_id);


--
-- Name: IX_video_thumbnail_map_video_id_image_id; Type: INDEX; Schema: public; Owner: root
--

CREATE UNIQUE INDEX "IX_video_thumbnail_map_video_id_image_id" ON public.video_thumbnail_map USING btree (video_id, image_id);


--
-- Name: channel_avatar_map FK_channel_avatar_map_channel_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_avatar_map
    ADD CONSTRAINT "FK_channel_avatar_map_channel_channel_id" FOREIGN KEY (channel_id) REFERENCES public.channel(id) ON DELETE CASCADE;


--
-- Name: channel_avatar_map FK_channel_avatar_map_image_image_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_avatar_map
    ADD CONSTRAINT "FK_channel_avatar_map_image_image_id" FOREIGN KEY (image_id) REFERENCES public.image(id) ON DELETE CASCADE;


--
-- Name: channel_banner_map FK_channel_banner_map_channel_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_banner_map
    ADD CONSTRAINT "FK_channel_banner_map_channel_channel_id" FOREIGN KEY (channel_id) REFERENCES public.channel(id) ON DELETE CASCADE;


--
-- Name: channel_banner_map FK_channel_banner_map_image_image_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.channel_banner_map
    ADD CONSTRAINT "FK_channel_banner_map_image_image_id" FOREIGN KEY (image_id) REFERENCES public.image(id) ON DELETE CASCADE;


--
-- Name: scoped_group FK_scoped_group_scoped_group_parent_group_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_group
    ADD CONSTRAINT "FK_scoped_group_scoped_group_parent_group_id" FOREIGN KEY (parent_group_id) REFERENCES public.scoped_group(id) ON DELETE RESTRICT;


--
-- Name: scoped_group FK_scoped_group_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_group
    ADD CONSTRAINT "FK_scoped_group_user_user_id" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: scoped_local_playlist FK_scoped_local_playlist_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_local_playlist
    ADD CONSTRAINT "FK_scoped_local_playlist_user_user_id" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: scoped_local_playlist_video_map FK_scoped_local_playlist_video_map_scoped_local_playlist_local~; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_local_playlist_video_map
    ADD CONSTRAINT "FK_scoped_local_playlist_video_map_scoped_local_playlist_local~" FOREIGN KEY (local_playlist_id) REFERENCES public.scoped_local_playlist(id) ON DELETE CASCADE;


--
-- Name: scoped_local_playlist_video_map FK_scoped_local_playlist_video_map_video_video_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_local_playlist_video_map
    ADD CONSTRAINT "FK_scoped_local_playlist_video_map_video_video_id" FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- Name: scoped_subscription FK_scoped_subscription_channel_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription
    ADD CONSTRAINT "FK_scoped_subscription_channel_channel_id" FOREIGN KEY (channel_id) REFERENCES public.channel(id) ON DELETE CASCADE;


--
-- Name: scoped_subscription_group_map FK_scoped_subscription_group_map_scoped_group_group_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription_group_map
    ADD CONSTRAINT "FK_scoped_subscription_group_map_scoped_group_group_id" FOREIGN KEY (group_id) REFERENCES public.scoped_group(id) ON DELETE CASCADE;


--
-- Name: scoped_subscription_group_map FK_scoped_subscription_group_map_scoped_subscription_subscript~; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription_group_map
    ADD CONSTRAINT "FK_scoped_subscription_group_map_scoped_subscription_subscript~" FOREIGN KEY (subscription_id) REFERENCES public.scoped_subscription(id) ON DELETE CASCADE;


--
-- Name: scoped_subscription FK_scoped_subscription_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_subscription
    ADD CONSTRAINT "FK_scoped_subscription_user_user_id" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: scoped_watching_history FK_scoped_watching_history_user_user_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_watching_history
    ADD CONSTRAINT "FK_scoped_watching_history_user_user_id" FOREIGN KEY (user_id) REFERENCES public."user"(id) ON DELETE CASCADE;


--
-- Name: scoped_watching_history FK_scoped_watching_history_video_video_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.scoped_watching_history
    ADD CONSTRAINT "FK_scoped_watching_history_video_video_id" FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- Name: stream FK_stream_enum_audio_codec_audio_codec_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_audio_codec_audio_codec_id" FOREIGN KEY (audio_codec_id) REFERENCES public.enum_audio_codec(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_enum_audio_quality_audio_quality_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_audio_quality_audio_quality_id" FOREIGN KEY (audio_quality_id) REFERENCES public.enum_audio_quality(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_enum_projection_type_projection_type_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_projection_type_projection_type_id" FOREIGN KEY (projection_type_id) REFERENCES public.enum_projection_type(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_enum_stream_type_stream_type_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_stream_type_stream_type_id" FOREIGN KEY (stream_type_id) REFERENCES public.enum_stream_type(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_enum_video_codec_video_codec_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_video_codec_video_codec_id" FOREIGN KEY (video_codec_id) REFERENCES public.enum_video_codec(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_enum_video_container_container_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_enum_video_container_container_id" FOREIGN KEY (container_id) REFERENCES public.enum_video_container(id) ON DELETE RESTRICT;


--
-- Name: stream FK_stream_video_video_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.stream
    ADD CONSTRAINT "FK_stream_video_video_id" FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- Name: video_caption FK_video_caption_video_video_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video_caption
    ADD CONSTRAINT "FK_video_caption_video_video_id" FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- Name: video FK_video_channel_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video
    ADD CONSTRAINT "FK_video_channel_channel_id" FOREIGN KEY (channel_id) REFERENCES public.channel(id) ON DELETE SET NULL;


--
-- Name: video_thumbnail_map FK_video_thumbnail_map_image_image_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video_thumbnail_map
    ADD CONSTRAINT "FK_video_thumbnail_map_image_image_id" FOREIGN KEY (image_id) REFERENCES public.image(id) ON DELETE CASCADE;


--
-- Name: video_thumbnail_map FK_video_thumbnail_map_video_video_id; Type: FK CONSTRAINT; Schema: public; Owner: root
--

ALTER TABLE ONLY public.video_thumbnail_map
    ADD CONSTRAINT "FK_video_thumbnail_map_video_video_id" FOREIGN KEY (video_id) REFERENCES public.video(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict rV8zTc9lXWsm1Xmff6GTO6HCh42kFpyY7djzu2e30KT3T7Nqe57IDmn0HYElrEb

