using TMS.Apps.FrontTube.Backend.Common.ProviderCore.Contracts;
using TMS.Apps.FrontTube.Backend.Providers.Invidious.ApiModels;

namespace TMS.Apps.FrontTube.Backend.Providers.Invidious.Mappers;

/// <summary>
/// Maps Invidious caption DTOs to common CaptionInfo contracts.
/// </summary>
public static class CaptionMapper
{
    /// <summary>
    /// Maps an Invidious video caption DTO to a CaptionInfo contract.
    /// </summary>
    public static CaptionMetadata ToCaptionInfo(InvidiousVideoCaptionDto dto, Uri baseUrl)
    {
        var captionUrl = dto.Url.StartsWith("http", StringComparison.OrdinalIgnoreCase)
            ? new Uri(dto.Url)
            : new Uri($"{baseUrl.ToString().TrimEnd('/')}{dto.Url}");

        return new CaptionMetadata
        {
            Name = dto.Label,
            LanguageCode = dto.LanguageCode,
            AbsoluteRemoteUrl = captionUrl,
            IsAutoGenerated = dto.Label.Contains("auto", StringComparison.OrdinalIgnoreCase)
        };
    }
}
