using TMS.Apps.Web.OutVidious.Common.ProvidersCore.Contracts;
using TMS.Apps.Web.OutVidious.Providers.Invidious.ApiModels;

namespace TMS.Apps.Web.OutVidious.Providers.Invidious.Mappers;

/// <summary>
/// Maps Invidious caption DTOs to common CaptionInfo contracts.
/// </summary>
public static class CaptionMapper
{
    /// <summary>
    /// Maps an Invidious video caption DTO to a CaptionInfo contract.
    /// </summary>
    public static CaptionInfo ToCaptionInfo(InvidiousVideoCaptionDto dto, Uri baseUrl)
    {
        var captionUrl = dto.Url.StartsWith("http", StringComparison.OrdinalIgnoreCase)
            ? new Uri(dto.Url)
            : new Uri($"{baseUrl.ToString().TrimEnd('/')}{dto.Url}");

        return new CaptionInfo
        {
            Label = dto.Label,
            LanguageCode = dto.LanguageCode,
            Url = captionUrl,
            IsAutoGenerated = dto.Label.Contains("auto", StringComparison.OrdinalIgnoreCase)
        };
    }
}
